server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XXFatai/springcloud-demo
          search-paths: config-files
          basedir: tmp/
  security:
    user:
      name: username
      password: password
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://username:password@localhost:8761/eureka